package com.ebupt.yuebox.model;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table SETUP_TASK.
 */
public class SetupTask {

    /** Not-null value. */
    private String task_id;
    private Long task_publish_time;
    private Long task_start_time;
    private Long task_end_time;
    private String task_client_name;
    private String task_client_address;
    private Integer task_client_lng;
    private Integer task_client_lat;
    private String task_client_tel;
    private String task_client_mobile;
    private Integer task_box_num;
    private String task_get_userid;
    private String task_status;
    private Integer task_grab_credits;
    private Integer task_finish_credits;
    private Double task_finish_comment_factor;
    private String task_finish_comment;
    private String task_boxids;
    private Long task_edittime;
    private String task_client_person;
    private String task_outstorage_id;

    public SetupTask() {
    }

    public SetupTask(String task_id) {
        this.task_id = task_id;
    }

    public SetupTask(String task_id, Long task_publish_time, Long task_start_time, Long task_end_time, String task_client_name, String task_client_address, Integer task_client_lng, Integer task_client_lat, String task_client_tel, String task_client_mobile, Integer task_box_num, String task_get_userid, String task_status, Integer task_grab_credits, Integer task_finish_credits, Double task_finish_comment_factor, String task_finish_comment, String task_boxids, Long task_edittime, String task_client_person, String task_outstorage_id) {
        this.task_id = task_id;
        this.task_publish_time = task_publish_time;
        this.task_start_time = task_start_time;
        this.task_end_time = task_end_time;
        this.task_client_name = task_client_name;
        this.task_client_address = task_client_address;
        this.task_client_lng = task_client_lng;
        this.task_client_lat = task_client_lat;
        this.task_client_tel = task_client_tel;
        this.task_client_mobile = task_client_mobile;
        this.task_box_num = task_box_num;
        this.task_get_userid = task_get_userid;
        this.task_status = task_status;
        this.task_grab_credits = task_grab_credits;
        this.task_finish_credits = task_finish_credits;
        this.task_finish_comment_factor = task_finish_comment_factor;
        this.task_finish_comment = task_finish_comment;
        this.task_boxids = task_boxids;
        this.task_edittime = task_edittime;
        this.task_client_person = task_client_person;
        this.task_outstorage_id = task_outstorage_id;
    }

    /** Not-null value. */
    public String getTask_id() {
        return task_id;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setTask_id(String task_id) {
        this.task_id = task_id;
    }

    public Long getTask_publish_time() {
        return task_publish_time;
    }

    public void setTask_publish_time(Long task_publish_time) {
        this.task_publish_time = task_publish_time;
    }

    public Long getTask_start_time() {
        return task_start_time;
    }

    public void setTask_start_time(Long task_start_time) {
        this.task_start_time = task_start_time;
    }

    public Long getTask_end_time() {
        return task_end_time;
    }

    public void setTask_end_time(Long task_end_time) {
        this.task_end_time = task_end_time;
    }

    public String getTask_client_name() {
        return task_client_name;
    }

    public void setTask_client_name(String task_client_name) {
        this.task_client_name = task_client_name;
    }

    public String getTask_client_address() {
        return task_client_address;
    }

    public void setTask_client_address(String task_client_address) {
        this.task_client_address = task_client_address;
    }

    public Integer getTask_client_lng() {
        return task_client_lng;
    }

    public void setTask_client_lng(Integer task_client_lng) {
        this.task_client_lng = task_client_lng;
    }

    public Integer getTask_client_lat() {
        return task_client_lat;
    }

    public void setTask_client_lat(Integer task_client_lat) {
        this.task_client_lat = task_client_lat;
    }

    public String getTask_client_tel() {
        return task_client_tel;
    }

    public void setTask_client_tel(String task_client_tel) {
        this.task_client_tel = task_client_tel;
    }

    public String getTask_client_mobile() {
        return task_client_mobile;
    }

    public void setTask_client_mobile(String task_client_mobile) {
        this.task_client_mobile = task_client_mobile;
    }

    public Integer getTask_box_num() {
        return task_box_num;
    }

    public void setTask_box_num(Integer task_box_num) {
        this.task_box_num = task_box_num;
    }

    public String getTask_get_userid() {
        return task_get_userid;
    }

    public void setTask_get_userid(String task_get_userid) {
        this.task_get_userid = task_get_userid;
    }

    public String getTask_status() {
        return task_status;
    }

    public void setTask_status(String task_status) {
        this.task_status = task_status;
    }

    public Integer getTask_grab_credits() {
        return task_grab_credits;
    }

    public void setTask_grab_credits(Integer task_grab_credits) {
        this.task_grab_credits = task_grab_credits;
    }

    public Integer getTask_finish_credits() {
        return task_finish_credits;
    }

    public void setTask_finish_credits(Integer task_finish_credits) {
        this.task_finish_credits = task_finish_credits;
    }

    public Double getTask_finish_comment_factor() {
        return task_finish_comment_factor;
    }

    public void setTask_finish_comment_factor(Double task_finish_comment_factor) {
        this.task_finish_comment_factor = task_finish_comment_factor;
    }

    public String getTask_finish_comment() {
        return task_finish_comment;
    }

    public void setTask_finish_comment(String task_finish_comment) {
        this.task_finish_comment = task_finish_comment;
    }

    public String getTask_boxids() {
        return task_boxids;
    }

    public void setTask_boxids(String task_boxids) {
        this.task_boxids = task_boxids;
    }

    public Long getTask_edittime() {
        return task_edittime;
    }

    public void setTask_edittime(Long task_edittime) {
        this.task_edittime = task_edittime;
    }

    public String getTask_client_person() {
        return task_client_person;
    }

    public void setTask_client_person(String task_client_person) {
        this.task_client_person = task_client_person;
    }

    public String getTask_outstorage_id() {
        return task_outstorage_id;
    }

    public void setTask_outstorage_id(String task_outstorage_id) {
        this.task_outstorage_id = task_outstorage_id;
    }

}
