package com.ebupt.yuebox.database;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.ebupt.yuebox.database.AppSetupUserDao;
import com.ebupt.yuebox.database.SetupTaskDao;
import com.ebupt.yuebox.database.WodAppPictureDao;
import com.ebupt.yuebox.model.SetupTask;
import com.ebupt.yuebox.model.AppSetupUser;
import com.ebupt.yuebox.model.WodAppPicture;


// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig setupTaskDaoConfig;
    private final DaoConfig appSetupUserDaoConfig;
    private final DaoConfig wodAppPictureDaoConfig;

    private final SetupTaskDao setupTaskDao;
    private final AppSetupUserDao appSetupUserDao;
    private final WodAppPictureDao wodAppPictureDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        setupTaskDaoConfig = daoConfigMap.get(SetupTaskDao.class).clone();
        setupTaskDaoConfig.initIdentityScope(type);

        appSetupUserDaoConfig = daoConfigMap.get(AppSetupUserDao.class).clone();
        appSetupUserDaoConfig.initIdentityScope(type);

        wodAppPictureDaoConfig = daoConfigMap.get(WodAppPictureDao.class).clone();
        wodAppPictureDaoConfig.initIdentityScope(type);

        setupTaskDao = new SetupTaskDao(setupTaskDaoConfig, this);
        appSetupUserDao = new AppSetupUserDao(appSetupUserDaoConfig, this);
        wodAppPictureDao = new WodAppPictureDao(wodAppPictureDaoConfig, this);

        registerDao(SetupTask.class, setupTaskDao);
        registerDao(AppSetupUser.class, appSetupUserDao);
        registerDao(WodAppPicture.class, wodAppPictureDao);
    }
    
    public void clear() {
        setupTaskDaoConfig.getIdentityScope().clear();
        appSetupUserDaoConfig.getIdentityScope().clear();
        wodAppPictureDaoConfig.getIdentityScope().clear();
    }

    public SetupTaskDao getSetupTaskDao() {
        return setupTaskDao;
    }

    public AppSetupUserDao getAppSetupUserDao() {
        return appSetupUserDao;
    }

    public WodAppPictureDao getWodAppPictureDao() {
        return wodAppPictureDao;
    }

}
