package com.ebupt.yuebox.model;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table WOD_APP_PICTURE.
 */
public class WodAppPicture {

    /** Not-null value. */
    private String picture_id;
    private Long picture_uptime;
    private String picture_name;
    private String picture_url;
    private Long picture_task_id;
    private Long picture_user_id;

    public WodAppPicture() {
    }

    public WodAppPicture(String picture_id) {
        this.picture_id = picture_id;
    }

    public WodAppPicture(String picture_id, Long picture_uptime, String picture_name, String picture_url, Long picture_task_id, Long picture_user_id) {
        this.picture_id = picture_id;
        this.picture_uptime = picture_uptime;
        this.picture_name = picture_name;
        this.picture_url = picture_url;
        this.picture_task_id = picture_task_id;
        this.picture_user_id = picture_user_id;
    }

    /** Not-null value. */
    public String getPicture_id() {
        return picture_id;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setPicture_id(String picture_id) {
        this.picture_id = picture_id;
    }

    public Long getPicture_uptime() {
        return picture_uptime;
    }

    public void setPicture_uptime(Long picture_uptime) {
        this.picture_uptime = picture_uptime;
    }

    public String getPicture_name() {
        return picture_name;
    }

    public void setPicture_name(String picture_name) {
        this.picture_name = picture_name;
    }

    public String getPicture_url() {
        return picture_url;
    }

    public void setPicture_url(String picture_url) {
        this.picture_url = picture_url;
    }

    public Long getPicture_task_id() {
        return picture_task_id;
    }

    public void setPicture_task_id(Long picture_task_id) {
        this.picture_task_id = picture_task_id;
    }

    public Long getPicture_user_id() {
        return picture_user_id;
    }

    public void setPicture_user_id(Long picture_user_id) {
        this.picture_user_id = picture_user_id;
    }

}
